slides:
	xelatex  tutorial
	bibtex  tutorial
	xelatex  tutorial
	xelatex  tutorial

clean:
	rm -f *.log *.aux *.bbl *.blg *.out tutorial*.pdf *.dvi *.fdb* *.fls *.synctex.gz *.rum.xml *.snm *.vrb *.nav *.toc
